// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dQVQPOOOOQO'#Co'#CoQVQPOOOeQQO'#CbOjQQO'#CeOOQO'#Ca'#CaOoQPO'#C`OOQO'#C`'#C`QzQPO'#CpQYQPOOOOQO-E6m-E6mOOQO,58|,58|OOQO'#Cg'#CgO!PQQO,59POOQO,58z,58zO!UQPO,59[OOQO-E6n-E6nOOQO'#Ch'#ChO!gQPO1G.kO!PQQO'#CqO!oQPO7+$VO!wQQO7+$VOOQO,59],59]OOQO-E6o-E6oO#YQQO<<GqOOQO'#Cj'#CjO#kQPO'#CkOOQO<<Gq<<GqOOQOAN=]AN=]OOQO'#Cl'#ClO#pQPO,59VO#kQPO1G.qO#uQPO7+$]OOQO<<Gw<<Gw",
  stateData: "#z~OPOS~ORPOVROYSObVO~OWZO~OW[O~Ob^ORSXfSX~ORPO~OWaO~ORPOVdaYdabdafda~O]eOhcO~O]hOhcO~OWiOijORXqbXqfXq~OWiOijORXybXyfXy~OamO~OhoO~OjqO~O",
  goto: "!tfPPPPglqPPqPvyP!P!P!VPP!]!g!nVWOQXVUOQXVTOQXR]SQb]RfcQkeRlhQnjRpoQQOSYQ_R_WSXOQR`XQdbRgd",
  nodeNames: "⚠ WhiteSpace Program Newline Statement Declaration entityDecl Entity Identifier attributeDecl Attribute EntityRef AttributeName AttributeType CompositionArg CardinalityArg CardinalityValue Number LineComment",
  maxTerm: 26,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "3z~RqXY#YYZ#h]^#Ypq#Yxy#pyz#u|}#z}!O$P!P!Q$_!Q![$V!c!e$|!e!f%n!f!g&|!g!o$|!o!p'n!p!q$|!q!r%n!r!s(`!s!u$|!u!v%n!v!w$|!w!x(`!x!}$|#R#S$|#T#U)Q#U#X$|#X#Y/Y#Y#b$|#b#c3^#c#o$|%W;'S$|;'S;=`%h<%lO$|~#_RP~XY#Y]^#Ypq#Y~#mPR~YZ#h~#uOi~~#zOj~~$POh~P$SP!Q![$VP$[PaP!Q![$V~$bP!P!Q$e~$jSb~OY$eZ;'S$e;'S;=`$v<%lO$e~$yP;=`<%l$eQ%RVWQ!Q![$|!c!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|Q%kP;=`<%l$|R%sXWQ!Q![$|!c!r$|!r!s&`!s!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R&gV]PWQ!Q![$|!c!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R'RXWQ!Q![$|!c!t$|!t!u&`!u!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R'sXWQ!Q![$|!c!x$|!x!y&`!y!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R(eXWQ!Q![$|!c!m$|!m!n&`!n!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R)VXWQ!Q![$|!c!}$|#R#S$|#T#h$|#h#i)r#i#o$|%W;'S$|;'S;=`%h<%lO$|R)wXWQ!Q![$|!c!}$|#R#S$|#T#h$|#h#i*d#i#o$|%W;'S$|;'S;=`%h<%lO$|R*iXWQ!Q![$|!c!}$|#R#S$|#T#f$|#f#g+U#g#o$|%W;'S$|;'S;=`%h<%lO$|R+ZXWQ!Q![$|!c!}$|#R#S$|#T#]$|#]#^+v#^#o$|%W;'S$|;'S;=`%h<%lO$|R+{XWQ!Q![$|!c!}$|#R#S$|#T#U$|#U#V,h#V#o$|%W;'S$|;'S;=`%h<%lO$|R,mXWQ!Q![$|!c!}$|#R#S$|#T#i$|#i#j-Y#j#o$|%W;'S$|;'S;=`%h<%lO$|R-_XWQ!Q![$|!c!}$|#R#S$|#T#h$|#h#i-z#i#o$|%W;'S$|;'S;=`%h<%lO$|R.PXWQ!Q![$|!c!}$|#R#S$|#T#X$|#X#Y.l#Y#o$|%W;'S$|;'S;=`%h<%lO$|R.sVYPWQ!Q![$|!c!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R/_XWQ!Q![$|!c!}$|#R#S$|#T#b$|#b#c/z#c#o$|%W;'S$|;'S;=`%h<%lO$|R0PXWQ!Q![$|!c!}$|#R#S$|#T#h$|#h#i0l#i#o$|%W;'S$|;'S;=`%h<%lO$|R0qXWQ!Q![$|!c!}$|#R#S$|#T#]$|#]#^1^#^#o$|%W;'S$|;'S;=`%h<%lO$|R1cXWQ!Q![$|!c!}$|#R#S$|#T#h$|#h#i2O#i#o$|%W;'S$|;'S;=`%h<%lO$|R2TXWQ!Q![$|!c!}$|#R#S$|#T#m$|#m#n2p#n#o$|%W;'S$|;'S;=`%h<%lO$|R2wVVPWQ!Q![$|!c!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|R3eVWQaP!Q![$|!c!}$|#R#S$|#T#o$|%W;'S$|;'S;=`%h<%lO$|",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
