// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%dQVQPOOOOQO'#Co'#CoQVQPOOOeQQO'#CbOjQQO'#CeOOQO'#Ca'#CaOoQPO'#C`OOQO'#C`'#C`QzQPO'#CpQYQPOOOOQO-E6m-E6mOOQO,58|,58|OOQO'#Cg'#CgO!PQQO,59POOQO,58z,58zO!UQPO,59[OOQO-E6n-E6nOOQO'#Ch'#ChO!gQPO1G.kO!PQQO'#CqO!oQPO7+$VO!wQQO7+$VOOQO,59],59]OOQO-E6o-E6oO#YQQO<<GqOOQO'#Cj'#CjO#kQQO'#CkOOQO<<Gq<<GqOOQOAN=]AN=]OOQO'#Cl'#ClO#sQPO,59VO#kQQO1G.qO#xQPO7+$]OOQO<<Gw<<Gw",
  stateData: "#}~OPOS~ORPOVROYSObVO~OWZO~OW[O~Ob^ORSXfSX~ORPO~OWaO~ORPOVdaYdabdafda~O]eOhcO~O]hOhcO~OWiOijORXqbXqfXq~OWiOijORXybXyfXy~OWmOamO~OhoO~OjqO~O",
  goto: "!tfPPPPglqPPqPvyP!P!P!VPP!]!g!nVWOQXVUOQXVTOQXR]SQb]RfcQkeRlhQnjRpoQQOSYQ_R_WSXOQR`XQdbRgd",
  nodeNames: "⚠ WhiteSpace Program Newline Statement Declaration entityDecl Entity Identifier attributeDecl Attribute EntityRef AttributeName AttributeType CompositionArg CardinalityArg CardinalityValue Number LineComment",
  maxTerm: 26,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "3W~RoXY#SYZ#b]^#Spq#Sxy#jyz#o|}#t}!O#y!P!Q$X!Q![$P!c!e$v!e!f%h!f!g&v!g!o$v!o!p'h!p!q$v!q!r%h!r!s(Y!s!u$v!u!v%h!v!w$v!w!x(Y!x!}$v#R#S$v#T#U(z#U#X$v#X#Y/S#Y#o$v%W;'S$v;'S;=`%b<%lO$v~#XRP~XY#S]^#Spq#S~#gPR~YZ#b~#oOi~~#tOj~~#yOh~~#|P!Q![$P~$UPa~!Q![$P~$[P!P!Q$_~$dSb~OY$_Z;'S$_;'S;=`$p<%lO$_~$sP;=`<%l$_Q${VWQ!Q![$v!c!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vQ%eP;=`<%l$vR%mXWQ!Q![$v!c!r$v!r!s&Y!s!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR&aV]PWQ!Q![$v!c!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR&{XWQ!Q![$v!c!t$v!t!u&Y!u!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR'mXWQ!Q![$v!c!x$v!x!y&Y!y!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR(_XWQ!Q![$v!c!m$v!m!n&Y!n!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR)PXWQ!Q![$v!c!}$v#R#S$v#T#h$v#h#i)l#i#o$v%W;'S$v;'S;=`%b<%lO$vR)qXWQ!Q![$v!c!}$v#R#S$v#T#h$v#h#i*^#i#o$v%W;'S$v;'S;=`%b<%lO$vR*cXWQ!Q![$v!c!}$v#R#S$v#T#f$v#f#g+O#g#o$v%W;'S$v;'S;=`%b<%lO$vR+TXWQ!Q![$v!c!}$v#R#S$v#T#]$v#]#^+p#^#o$v%W;'S$v;'S;=`%b<%lO$vR+uXWQ!Q![$v!c!}$v#R#S$v#T#U$v#U#V,b#V#o$v%W;'S$v;'S;=`%b<%lO$vR,gXWQ!Q![$v!c!}$v#R#S$v#T#i$v#i#j-S#j#o$v%W;'S$v;'S;=`%b<%lO$vR-XXWQ!Q![$v!c!}$v#R#S$v#T#h$v#h#i-t#i#o$v%W;'S$v;'S;=`%b<%lO$vR-yXWQ!Q![$v!c!}$v#R#S$v#T#X$v#X#Y.f#Y#o$v%W;'S$v;'S;=`%b<%lO$vR.mVYPWQ!Q![$v!c!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$vR/XXWQ!Q![$v!c!}$v#R#S$v#T#b$v#b#c/t#c#o$v%W;'S$v;'S;=`%b<%lO$vR/yXWQ!Q![$v!c!}$v#R#S$v#T#h$v#h#i0f#i#o$v%W;'S$v;'S;=`%b<%lO$vR0kXWQ!Q![$v!c!}$v#R#S$v#T#]$v#]#^1W#^#o$v%W;'S$v;'S;=`%b<%lO$vR1]XWQ!Q![$v!c!}$v#R#S$v#T#h$v#h#i1x#i#o$v%W;'S$v;'S;=`%b<%lO$vR1}XWQ!Q![$v!c!}$v#R#S$v#T#m$v#m#n2j#n#o$v%W;'S$v;'S;=`%b<%lO$vR2qVVPWQ!Q![$v!c!}$v#R#S$v#T#o$v%W;'S$v;'S;=`%b<%lO$v",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
