// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "tQYQPOOO_QQO'#C`OOQO'#Cc'#CcQYQPOOOOQO,58z,58zOOQO-E6a-E6a",
  stateData: "d~OPOSQOS~OTPO~OUSO~O",
  goto: "cWPPPPXPP]TQORQRORTR",
  nodeNames: "⚠ WhiteSpace Newline Program entityDecl Entity Identifier",
  maxTerm: 9,
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "%c~RXXYnYZ|]^npqn!c!}!U#R#S!U#T#X!U#X#Y!g#Y#o!U~sRP~XYn]^npqn~!RPQ~YZ|Q!ZSUQ!Q![!U!c!}!U#R#S!U#T#o!UR!lUUQ!Q![!U!c!}!U#R#S!U#T#b!U#b#c#O#c#o!UR#TUUQ!Q![!U!c!}!U#R#S!U#T#h!U#h#i#g#i#o!UR#lUUQ!Q![!U!c!}!U#R#S!U#T#]!U#]#^$O#^#o!UR$TUUQ!Q![!U!c!}!U#R#S!U#T#h!U#h#i$g#i#o!UR$lUUQ!Q![!U!c!}!U#R#S!U#T#m!U#m#n%O#n#o!UR%VSTPUQ!Q![!U!c!}!U#R#S!U#T#o!U",
  tokenizers: [0, 1],
  topRules: {"Program":[0,3]},
  tokenPrec: 0
})
