// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  WhiteSpace = 1,
  Newline = 2,
  Program = 3,
  entityDecl = 4,
  Entity = 5,
  Identifier = 6,
  LineComment = 7
